apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemlisting-deployment
  labels:
    app: MenuItemListing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemListing  
  template:
    metadata:
      labels:
        app: MenuItemListing
    spec:
      containers:
      - name: myregistryforict
        image: myregistryforict.azurecr.io/menuitemlisting:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: secret-acr
---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlistingsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemListing